### ISSUE TITLE
"napi_alloc_skb" error on make commands

### ISSUE THREAD

**Issue by DTseven** [rickhofstede/linksys_usb3gigv1_linux#1]
Hello, Thanks for your work. I'm almost new to Linux and new to GitHub but i will try to tell what i had to do to get this working!

uname -r gives: 3.16.0-77-generic

when trying to `make` as you explained, i ran into **following error**

```
linksys_usb3gigv1_linux/r8152.c:1965:13: error: implicit declaration of function ‘napi_alloc_skb’ [-Werror=implicit-function-declaration]
             skb = napi_alloc_skb(&tp->napi, pkt_len);
```
This made progress impossible, so i investigated further (no programming skills) and found this: `napi_alloc_skb` is a **missing function** that should be defined somewhere in a file called `skbuff.h` somewhere in _/lib/kernel_ .. (according to [this](http://lxr.free-electrons.com/ident?i=napi_alloc_skb)).
In my own `skbuff.h` file, i could not find the function defined! 

What i could find:
In a [git-commit](http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=e2338f86b334558b9f38a20a06fc645d90d6da2d) that seemed involving some realtek drivers they were talking about it being the successor of `netdev_alloc_skb` which i could find in my own _skbuff.h_ file. So i modified your file _r8152.c_ from `napi_alloc_skb(&tp->napi, pkt_len)` to `netdev_alloc_skb(&tp->napi, pkt_len)` and ran `make` and `make install` again.

The execution did not fail but continue with an alert telling me it would accept my changed parameters (defined incorrectly but still recognized correctly). No errors from there...

As of now, everything is working as it should, all systems up and running :dancing_men: 

Can you give me a little further insight into the matter? I have no idea what all that actually means. At least it seems i did not break anything. If this is a legit issue, i'd love to see your code updated :D

**Comment by rickhofstede** [comment]
Good to hear that everything worked out for you in the end. From one of the links you posted ([this one](http://lxr.free-electrons.com/ident?v=3.19;i=napi_alloc_skb)), you can conclude that `napi_alloc_skb` was introduced in the v3.19 kernel, while you are running a v3.16 kernel. I assume that compilation will succeed out of the box once you upgrade to at least v3.19.
