### ISSUE TITLE
Kernel 4.10

### ISSUE THREAD

**Issue by beledouxdenis** [rickhofstede/linksys_usb3gigv1_linux#2]
I came across this project when I tried to use the kernel 4.10RC3 on Ubuntu 16.04 with an USB-C Hub + ethernet Aukey (https://www.amazon.co.uk/Gigabit-Ethernet-Adapter-MacBook-Devices/dp/B00WFQPTLM/ref=sr_1_8?ie=UTF8&qid=1484249116&sr=8-8&keywords=aukey+usb-c+hub). 

With the default kernel of Ubuntu 16.04, 4.4, the hub worked plug-and-play, but with the driver `cdc_ether` and the speed of 100MB/s, while this is a gigabit ethernet adapter.

When I used the kernel 4.10RC3, the ethernet adapter was no longer working at all: Both drivers were loaded, `cdc_ether` and your `RTL8152` (meaning your driver is somehow already included in this new kernel).

When I unloaded the former driver, with the given instruction `modprobe -r cdc_ether` & `update-initramfs -u`, and a reboot, it then worked like a charm, with the 1000MB/s speed.

All this to say that this issue is not really for your driver, but to notify you (and possible other visitors that might came across the same issue) of my case, so if you are somehow involved in the development of the linux kernel, you could do something about it, or not :D.

**Comment by rickhofstede** [comment]
Thanks for your heads-up!

**Comment by SainaRez** [comment]
I am using a different device and in my case I actually didn't need to run ```modprobe -r cdc_ether``` I just had to run the update command: ```update-initramfs -u```
