### ISSUE TITLE
Install Issue in OSMC

### ISSUE THREAD

**Issue by ddagva** [rickhofstede/linksys_usb3gigv1_linux#4]
Hello, first things first: many thanks for releasing this! I'm new to Linux and this is my first ever post in GitHub.

I'm trying to install on a Raspberry Pi 2 Model B running OSMC following your procedure, but it fails at the `make` step, with the following error messages:

> osmc@osmc:~/linksys_usb3gigv1_linux$ sudo make
> make -C /lib/modules/4.4.27-5-osmc/build SUBDIRS=/home/osmc/linksys_usb3gigv1_linux modules
> make[1]: *** /lib/modules/4.4.27-5-osmc/build: No such file or directory.  Stop.
> Makefile:17: recipe for target 'modules' failed
> make: *** [modules] Error 2

In order to clone the repo in OSMC, which is based on a stripped-down version of Debian Jessie, I first had to `apt-get install git-core` and `build-essential` packages, after that it seemed to work as expected. Alas, something actually seem to have gone wrong because the /build folder wasn't created as expected.

Could you please advise what to do to overcome this issue? I'm eager to see this ethernet adapter finally work at full speed :-)

**Comment by rickhofstede** [comment]
This is an artifact of trying to install a kernel module on an RPi, as described [here](https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=90702). In short, to fix it, please run the following command first (as root):

```
mkdir /lib/modules/`uname -r`/build
```

By the way, there is no need to compile (`make`) as root. You only need root permissions when you install the driver (`make install`).

**Comment by ddagva** [comment]
Thanks for your reply. I did the `mkdir` as suggested, then followed the next install step with `make`.
Result:

> osmc@osmc:~/linksys_usb3gigv1_linux$ make
> make -C /lib/modules/4.4.27-5-osmc/build SUBDIRS=/home/osmc/linksys_usb3gigv1_linux modules
> make[1]: Entering directory '/lib/modules/4.4.27-5-osmc/build'
> make[1]: *** No rule to make target 'modules'.  Stop.
> make[1]: Leaving directory '/lib/modules/4.4.27-5-osmc/build'
> Makefile:17: recipe for target 'modules' failed
> make: *** [modules] Error 2

Any further suggestion most welcome!

**Comment by rickhofstede** [comment]
I suggest you to follow the steps described in [this thread](http://raspberrypi.stackexchange.com/questions/5230/getting-no-rule-to-make-target-modules-stop-error-when-running-makefile-w). Please report back on your results.

**Comment by ddagva** [comment]
Okay, I will. Thanks for your time.

**Comment by ddagva** [comment]
If I understand the suggested thread correctly, it seems I have to create a symbolic link with `ln -s`. But - sorry for the noobs question - from where to where? I'm getting a bit lost here.
Here is the folder path, with my actual system version:
`/lib/modules/4.4.27-5-osmc/`
Would you be kind enough to walk me through this?

**Comment by rickhofstede** [comment]
Can you please check out whether the followings paths exist on your system (e.g., by running `ls -l` on them):
* `/lib/modules/$(uname -r)/build`
* `/lib/modules/$(uname -r)/src`
* `/usr/src/$(uname -r)`

If you don't have the kernel sources available on your system (last listed path), you can grab a copy from [here](https://github.com/raspberrypi/linux/releases). If the aforementioned/listed directory in `/usr/src/` exists, you should create a symbolic link to there:

`sudo ln -s /home/pi/src/linux /lib/modules/$(uname -r)/build`

Otherwise, unpack the downloaded kernel source and create a symbolic to the extracted files (assuming you unpacked to `/home/user/kernel`):

`sudo ln -s /home/user/kernel /lib/modules/$(uname -r)/build`

**Comment by ddagva** [comment]
Sure can, apologies for the late reply.Here are the 3 `ls -l `outputs:

> osmc@osmc:/$ ls -l /lib/modules/$(uname -r)/build
> total 0
> lrwxrwxrwx 1 root root 34 Feb  1 21:29 kernel -> /lib/modules/4.4.27-5-osmc/kernel/
> lrwxrwxrwx 1 root root 18 Feb  1 23:29 linux -> /home/pi/src/linux
> osmc@osmc:/$ ls -l /lib/modules/$(uname -r)/src
> total 0
> osmc@osmc:/$ ls -l /usr/src/$(uname -r)
> ls: cannot access /usr/src/4.4.27-5-osmc: No such file or directory

To download and unpack the kernel source, I assumed to do it this way (but have no clue if it's correct):
> sudo apt-get source https://github.com/raspberrypi/linux/releases/tag/raspberrypi-kernel_1.20161215-1
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> E: You must put some 'source' URIs in your sources.list
> osmc@osmc:/usr/src$

I managed to add the following URI in sources.list using this:
`echo "deb-src http://apt.osmc.tv jessie main" | sudo tee -a /etc/apt/sources.list`
... but again, unsure about all this, especially deb-src, since complete noob. And then, upon
`sudo apt-get update`
... I got this

> W: Failed to fetch http://apt.osmc.tv/dists/jessie/InRelease  Unable to find expected entry 'main/source/Sources' in Release file (Wrong sources.list entry or malformed file)

The expected entry is actually not to be found there (ie no 'main/source' directory). The distros are there, but located directly under /main.

What can I do to overcome this? Many thanks for your help.

**Comment by rickhofstede** [comment]
First of all, the way you're attempting to fetch the kernel sources and how you added the package source to `sources.list` is wrong. Could you please remove the added line (from `/etc/apt/sources.list`) again to repair your package manager configuration?

After you repaired your `sources.list` file, please perform the following operations:
```
$ apt-get update
$ apt-cache search osmc | grep headers
```

The last command should show at least one package with the version number of your kernel: `4.4.27-5-oscm`. If so, install the package like this:
```
$ apt-get install rbp2-headers-4.4.27-5-osmc
```

**Comment by ddagva** [comment]
Glad to have your instructions to follow, which I did: restored `sources.list` and ran the update. The search operation gave only a single result that included my kernel's name, amongst a bunch of others:

> rbp2-headers-4.4.27-7-osmc - Header files related to Linux kernel, specifically,

`uname-r` output is 
> 4.4.27-7-osmc

I used this kernel version number in the command line, and the package installation completed successfully.
Please let me know the next step, and thank you so very much for your patient guidance.

**Comment by rickhofstede** [comment]
Since the header files have been installed now, I assume your driver build should complete successfully. You may double-check the contents of the previously investigated directories; they should include some files now.

**Comment by ddagva** [comment]
Unfortunately, it does not. When trying to run `make`, it gives the same error message than in my 2nd post 

> No rule to make target 'modules'

Something has changed, though: under /lib/modules, there are now 2 directories:

> 4.4.27-5-osmc
> 4.4.27-7-osmc

But when I run `make`, it tries to install in 4.4.27-5-osmc, it doesn't take into account the newly updated kernel version number:

> osmc@osmc:~/linksys_usb3gigv1_linux$ make
> make -C /lib/modules/4.4.27-5-osmc/build SUBDIRS=/home/osmc/linksys_usb3gigv1_linux modules
> make[1]: Entering directory '/lib/modules/4.4.27-5-osmc/build'
> make[1]: Nothing to be done for 'modules'.
> make[1]: Leaving directory '/lib/modules/4.4.27-5-osmc/build'

I've tried to manually change the kernel version in `Makefile`, and also add a 'build' directory, and even a 'modules' directory right under /build, in both directories, all to no avail.

Probably closer to the objective now, but still unable to go through. Looking forward for your kind advice.

**Comment by rickhofstede** [comment]
Can you please run `make clean` before running `make` (another time)? This should clean up the temporary files created before (that reference your previous kernel version).

**Comment by ddagva** [comment]
Here is the output of `make clean`:

> osmc@osmc:~/linksys_usb3gigv1_linux$ make clean
> make -C /lib/modules/4.4.27-7-osmc/build SUBDIRS=/home/osmc/linksys_usb3gigv1_linux clean
> make[1]: Entering directory '/lib/modules/4.4.27-7-osmc/build'
> make[1]: *** No rule to make target 'clean'.  Stop.
> make[1]: Leaving directory '/lib/modules/4.4.27-7-osmc/build'
> Makefile:24: recipe for target 'clean' failed
> make: *** [clean] Error 2

Running `make` a second time results in the same Error 2 output.

I've double-checked if the kernel files were actually present in their directory, and there they were; full path is:
/lib/modules/4.4.27-7-osmc/kernel/

I also tried to re-create the symbolic link, using this command:
`sudo ln -s /lib/modules/4.4.27-7-osmc/kernel /lib/modules/$(uname -r)/build`

... and then `make clean` and `make` again, with this result:

> make
> make -C /lib/modules/4.4.27-7-osmc/build SUBDIRS=/home/osmc/linksys_usb3gigv1_linux modules
> make[1]: Entering directory '/lib/modules/4.4.27-7-osmc/build'
> make[1]: *** No rule to make target 'modules'.  Stop.
> make[1]: Leaving directory '/lib/modules/4.4.27-7-osmc/build'
> Makefile:17: recipe for target 'modules' failed
> make: *** [modules] Error 2

Maybe it would be easier if you could see the whole filesystem, thus spot path issues and the like much quicker. I guess I could create a compressed "disk image", and send it to you. Would you agree with that?

**Comment by rickhofstede** [comment]
Please don't start creating symlinks yourself, as this will leave a mess on your filesystem. My feeling is that we're very close to success, so I propose the following steps:
* Remove the cloned Git repository/directory (as a work-around for `make clean`).
* Clone the Git repository again and follow the build instructions.

If it doesn't work yet, don't worry. Please perform the following steps:
* `ls -l /lib/modules/4.4.27-7-osmc`
* `ls -l /usr/src/linux-headers-4.4.27-7-osmc/`

A disk image wouldn't help too much, I'm afraid, since we don't only need to inspect files, but also need to run commands.
