### ISSUE TITLE
Are there any plans to upstream the driver?

### ISSUE THREAD

**Issue by vi** [rickhofstede/linksys_usb3gigv1_linux#6]
Or the official in-tree driver already got improved?

**Comment by rickhofstede** [comment]
Linksys still provides no Linux drivers for this USB device and has never replied to any upstreaming requests.

**Comment by vi** [comment]
I mean upstream to Linux kernel source. Is official blessing from Linksys a requirement for inclusion into Linux kernel?

**Comment by rickhofstede** [comment]
To be honest, I have no experience with that at all. Do you?

**Comment by vi** [comment]
No (or not yet) as well.

Maybe I can even try to do it on your behalf if I find the driver really superior compared to standard when I get the device. What license of this driver by the way? With GPLv2 it should be easier to get into the kernel.

**Comment by rickhofstede** [comment]
The driver is not my own; basically, it's the RealTek driver adapted to work with the Linksys device. The RealTek driver itself is [GPLv2](https://github.com/rickhofstede/linksys_usb3gigv1_linux/blob/master/r8152.c#L4-L6) indeed, but I don't know how that exactly works when I modified the code.

Have you already tested this driver by the way?

**Comment by vi** [comment]
I've ordered the device, but not received it yet.

> it's the RealTek driver adapted to work with the Linksys device. The RealTek driver itself is GPLv2 indeed

As a derived work on a GPLv2 thing, your driver must be GPLv2.
