### ISSUE TITLE
support for 16.04

### ISSUE THREAD

**Issue by AgenticJamesBond** [rickhofstede/linksys_usb3gigv1_linux#7]
I was wondering if there would ever be official support for 16.04

**Comment by rickhofstede** [comment]
Have you tested the driver on Ubuntu 16.04 already? I suppose it will just work. According to RealTek, which provides the upstream driver, the driver should work up to Linux kernel v4.8.

**Comment by jimnordb** [comment]
Can confirm this works for 16.04 LTS. but i am having problems that it keeps using cdc_ether instead after a reboot. When using `modprobe r8152` it goes back to using realtek one when replugging it.

**Comment by rickhofstede** [comment]
@jimnordb Have you already tried to blacklist the `cdc_ether` module? For Ubuntu, please have a look at [this example](https://askubuntu.com/questions/110341/how-to-blacklist-kernel-modules).
